%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

on:
    push:
        branches:
          - 'build-**'
          - 'debug-**'

jobs:
    ignite:
        uses: 'mk-pmb/ghabuild-simple-gradle-projects/.github/workflows/build.yaml@master'

...
